name: cfnat
version: 1.0.0

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  http: any
  provider: any
  intl: any
  flutter_rust_bridge: any
  file_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  ffigen: any

flutter:
  uses-material-design: true
  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-Regular.otf
        - asset: assets/fonts/MiSans-Medium.otf
          weight: 500
        - asset: assets/fonts/MiSans-Bold.otf
          weight: 700